### ISSUE TITLE
Unable to edit config file on remote server

### ISSUE THREAD

**Issue by jmenashe** [JavidPack/CheatSheet#42]
I have a remote server running on Ubuntu Server 18.04 where I host my Terraria TML server. This mod refers to a server config that can only be edited by local users, but this is not possible for me because my server has no GUI. I can't find the config file with my other mod configs so I can't edit it with a text editor either. Is there a way to generate the config on the server so that I can edit the file as needed?

**Comment by JavidPack** [comment]
I think we already talked about this elsewhere, but I forget if that was you.

The server config for CheatSheet is only used to hide the tools from everyone not connecting using localhost. As such, there is no point in editing the server config on a server host because no one would be able to use the mod if you enabled that config option. 

It is recommended to use HerosMod if you want to administer the tools in this mod. HerosMod has a permissions system that CheatSheet respects.
